# permissions for end users to edit podendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podendpoint-editor-role
rules:
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - podendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - podendpoints/status
  verbs:
  - get
