# permissions for end users to view podendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podendpoint-viewer-role
rules:
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - podendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - podendpoints/status
  verbs:
  - get
