# permissions for end users to view podwireguardendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podwireguardendpoint-viewer-role
rules:
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - podwireguardendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - podwireguardendpoints/status
  verbs:
  - get
