# TEMPORARY CONFIGURATION FOR GO 1.25.0 MIGRATION
# This configuration is designed to allow building with Go 1.25.0
# while deferring some compatibility fixes to follow-up PRs

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

run:
  timeout: 10m
  skip-dirs:
    - cmd/kube-egress-cni
    - cmd/kube-egress-cni-ipam
    - cmd/kube-egress-gateway-controller/cmd
    - cmd/kube-egress-gateway-daemon/cmd
    - cmd/kube-egress-gateway-cnimanager/cmd
    - controllers/cnimanager
    - controllers/daemon
    - controllers/manager
    - e2e/utils
    - e2e
    - api/v1alpha1

issues:
  exclude:
    - "^SA1019: .*is deprecated.*$"
    - "^QF1008:.*$"
    - "Error return value of .*Close.* is not checked"
