//
//MIT License
//
//Copyright (c) Microsoft Corporation.
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.2
// source: pkg/cniprotocol/cni.proto

package cniprotocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CNIAddRequest is the request for cni add function.
type CNIAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CNIAddRequest) Reset() {
	*x = CNIAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cniprotocol_cni_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CNIAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CNIAddRequest) ProtoMessage() {}

func (x *CNIAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_cni_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CNIAddRequest.ProtoReflect.Descriptor instead.
func (*CNIAddRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_cni_proto_rawDescGZIP(), []int{0}
}

func (x *CNIAddRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CNIAddResponse is the response for cni add function.
type CNIAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CNIAddResponse) Reset() {
	*x = CNIAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cniprotocol_cni_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CNIAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CNIAddResponse) ProtoMessage() {}

func (x *CNIAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_cni_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CNIAddResponse.ProtoReflect.Descriptor instead.
func (*CNIAddResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_cni_proto_rawDescGZIP(), []int{1}
}

func (x *CNIAddResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CNIDeleteRequest is the request for cni del function.
type CNIDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CNIDeleteRequest) Reset() {
	*x = CNIDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cniprotocol_cni_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CNIDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CNIDeleteRequest) ProtoMessage() {}

func (x *CNIDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_cni_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CNIDeleteRequest.ProtoReflect.Descriptor instead.
func (*CNIDeleteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_cni_proto_rawDescGZIP(), []int{2}
}

func (x *CNIDeleteRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CNIDeleteResponse is the response for cni del function.
type CNIDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CNIDeleteResponse) Reset() {
	*x = CNIDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cniprotocol_cni_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CNIDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CNIDeleteResponse) ProtoMessage() {}

func (x *CNIDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_cni_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CNIDeleteResponse.ProtoReflect.Descriptor instead.
func (*CNIDeleteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_cni_proto_rawDescGZIP(), []int{3}
}

func (x *CNIDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_cniprotocol_cni_proto protoreflect.FileDescriptor

var file_pkg_cniprotocol_cni_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6e, 0x69, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x63, 0x6e, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x43, 0x4e, 0x49,
	0x2e, 0x4b, 0x75, 0x62, 0x65, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x43, 0x4e, 0x49, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x0e, 0x43, 0x4e, 0x49, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x2c, 0x0a, 0x10, 0x43, 0x4e, 0x49, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2d, 0x0a,
	0x11, 0x43, 0x4e, 0x49, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xd8, 0x01, 0x0a,
	0x0a, 0x4e, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x06, 0x4e,
	0x69, 0x63, 0x41, 0x64, 0x64, 0x12, 0x2a, 0x2e, 0x43, 0x4e, 0x49, 0x2e, 0x4b, 0x75, 0x62, 0x65,
	0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x41, 0x7a,
	0x75, 0x72, 0x65, 0x2e, 0x43, 0x4e, 0x49, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2b, 0x2e, 0x43, 0x4e, 0x49, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x45, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x2e,
	0x43, 0x4e, 0x49, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67,
	0x0a, 0x06, 0x4e, 0x69, 0x63, 0x44, 0x65, 0x6c, 0x12, 0x2d, 0x2e, 0x43, 0x4e, 0x49, 0x2e, 0x4b,
	0x75, 0x62, 0x65, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x2e, 0x43, 0x4e, 0x49, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x43, 0x4e, 0x49, 0x2e, 0x4b, 0x75,
	0x62, 0x65, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x41, 0x7a, 0x75, 0x72, 0x65, 0x2e, 0x43, 0x4e, 0x49, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x2f, 0x6b, 0x75, 0x62, 0x65,
	0x2d, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6e, 0x69, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_cniprotocol_cni_proto_rawDescOnce sync.Once
	file_pkg_cniprotocol_cni_proto_rawDescData = file_pkg_cniprotocol_cni_proto_rawDesc
)

func file_pkg_cniprotocol_cni_proto_rawDescGZIP() []byte {
	file_pkg_cniprotocol_cni_proto_rawDescOnce.Do(func() {
		file_pkg_cniprotocol_cni_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_cniprotocol_cni_proto_rawDescData)
	})
	return file_pkg_cniprotocol_cni_proto_rawDescData
}

var file_pkg_cniprotocol_cni_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_cniprotocol_cni_proto_goTypes = []interface{}{
	(*CNIAddRequest)(nil),     // 0: CNI.KubeEgressGateway.Azure.CNIAddRequest
	(*CNIAddResponse)(nil),    // 1: CNI.KubeEgressGateway.Azure.CNIAddResponse
	(*CNIDeleteRequest)(nil),  // 2: CNI.KubeEgressGateway.Azure.CNIDeleteRequest
	(*CNIDeleteResponse)(nil), // 3: CNI.KubeEgressGateway.Azure.CNIDeleteResponse
}
var file_pkg_cniprotocol_cni_proto_depIdxs = []int32{
	0, // 0: CNI.KubeEgressGateway.Azure.NicService.NicAdd:input_type -> CNI.KubeEgressGateway.Azure.CNIAddRequest
	2, // 1: CNI.KubeEgressGateway.Azure.NicService.NicDel:input_type -> CNI.KubeEgressGateway.Azure.CNIDeleteRequest
	1, // 2: CNI.KubeEgressGateway.Azure.NicService.NicAdd:output_type -> CNI.KubeEgressGateway.Azure.CNIAddResponse
	3, // 3: CNI.KubeEgressGateway.Azure.NicService.NicDel:output_type -> CNI.KubeEgressGateway.Azure.CNIDeleteResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_cniprotocol_cni_proto_init() }
func file_pkg_cniprotocol_cni_proto_init() {
	if File_pkg_cniprotocol_cni_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_cniprotocol_cni_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CNIAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_cniprotocol_cni_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CNIAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_cniprotocol_cni_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CNIDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_cniprotocol_cni_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CNIDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_cniprotocol_cni_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_cniprotocol_cni_proto_goTypes,
		DependencyIndexes: file_pkg_cniprotocol_cni_proto_depIdxs,
		MessageInfos:      file_pkg_cniprotocol_cni_proto_msgTypes,
	}.Build()
	File_pkg_cniprotocol_cni_proto = out.File
	file_pkg_cniprotocol_cni_proto_rawDesc = nil
	file_pkg_cniprotocol_cni_proto_goTypes = nil
	file_pkg_cniprotocol_cni_proto_depIdxs = nil
}
