apiVersion: v1
kind: Secret
metadata:
  name: kube-egress-gateway-azure-cloud-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  azure-cloud-config.json: {{ .Values.config.azureCloudConfig | toJson | indent 4 | b64enc | quote }}