---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - gatewaylbconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - gatewaylbconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - gatewaylbconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - gatewayvmconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - gatewayvmconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - gatewayvmconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - staticgatewayconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - staticgatewayconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - staticgatewayconfigurations/status
  verbs:
  - get
  - patch
  - update
