---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - gatewaylbconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - gatewaylbconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - gatewaylbconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - gatewayvmconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - gatewayvmconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - gatewayvmconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - staticgatewayconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egressgateway.kubernetes.azure.com
  resources:
  - staticgatewayconfigurations/status
  verbs:
  - get
  - patch
  - update
