apiVersion: v1
entries:
  kube-egress-gateway:
  - apiVersion: v2
    created: "2023-07-06T07:59:09.474504466Z"
    dependencies:
    - alias: cert-manager
      condition: cert-manager.enabled
      name: cert-manager
      repository: https://charts.jetstack.io
      version: v1.11.0
    description: A Helm chart for installing Azure kube-egress-gateway components
    digest: 87894f5b8e6dc7b118946c936d23e058c35d5404e5e31f94ed06d97f7acaceb3
    maintainers:
    - email: jwtty0919@gmail.com
      name: Wantong Jiang
    - email: fanshangxiang@gmail.com
      name: Shangxiang Fan
    name: kube-egress-gateway
    sources:
    - https://github.com/Azure/kube-egress-gateway
    type: application
    urls:
    - kube-egress-gateway-0.1.0.tgz
    version: 0.1.0
generated: "2023-07-06T07:59:09.470455334Z"
