apiVersion: v1
entries:
  kube-egress-gateway:
  - apiVersion: v2
    created: "2023-04-06T06:14:42.599119029Z"
    dependencies:
    - alias: cert-manager
      condition: cert-manager.enabled
      name: cert-manager
      repository: https://charts.jetstack.io
      version: v1.11.0
    description: A Helm chart for installing Azure kube-egress-gateway components
    digest: e4431ca95b74cd63417fe532111e2182ce30a80c353406de3b50712c5693efbf
    maintainers:
    - email: jwtty0919@gmail.com
      name: Wantong Jiang
    - email: fanshangxiang@gmail.com
      name: Shangxiang Fan
    name: kube-egress-gateway
    sources:
    - https://github.com/Azure/kube-egress-gateway
    type: application
    urls:
    - kube-egress-gateway-0.1.0.tgz
    version: 0.1.0
generated: "2023-04-06T06:14:42.595677589Z"
