name: $(Date:yyyyMMdd)$(Rev:.r)_e2e

trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

variables:
- group: pod-egress-e2e
- group: aks-ci

pool: 1ES-AKS-DevInfra-Normal-Yellow

jobs:
- job: Run_KubeEgressGateway_E2E_CNIOverlay
  timeoutInMinutes: 149
  steps:
  - template: templates/e2e-steps.yml
    parameters:
      networkPlugin: 'overlay'
- job: Run_KubeEgressGateway_E2E_Nodesubnet
  timeoutInMinutes: 150
  steps:
  - template: templates/e2e-steps.yml
    parameters:
      networkPlugin: 'azure'
- job: Run_KubeEgressGateway_E2E_Cilium
  timeoutInMinutes: 150
  steps:
  - template: templates/e2e-steps.yml
    parameters:
      networkPlugin: 'cilium'
