name: $(Date:yyyyMMdd)$(Rev:.r)_e2e

trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool: kube-egress-gateway-e2e-pool

variables:
- group: pod-egress-e2e
- group: aks-ci

jobs:
- job: Run_KubeEgressGateway_E2E
  timeoutInMinutes: 150
  steps:
  - task: GoTool@0
    inputs:
      version: '1.24.3'
  - bash: |
      echo $(registry.password) | docker login $(registry.url) -u $(registry.username) --password-stdin
    displayName: docker login
  - template: templates/e2e-steps.yml
- job: Run_KubeEgressGateway_E2E_Nodesubnet
  timeoutInMinutes: 150
  steps:
  - task: GoTool@0
    inputs:
      version: '1.24.3'
  - bash: |
      echo $(registry.password) | docker login $(registry.url) -u $(registry.username) --password-stdin
    displayName: docker login
  - template: templates/e2e-steps.yml
    parameters:
      networkPlugin: 'azure'
- job: Run_KubeEgressGateway_E2E_Cilium
  timeoutInMinutes: 150
  steps:
  - task: GoTool@0
    inputs:
      version: '1.24.3'
  - bash: |
      echo $(registry.password) | docker login $(registry.url) -u $(registry.username) --password-stdin
    displayName: docker login
  - template: templates/e2e-steps.yml
    parameters:
      networkPlugin: 'cilium'

