name: $(Date:yyyyMMdd)$(Rev:.r)_e2e

trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool: kube-egress-gateway-e2e-pool

jobs:
- job: Run_KubeEgressGateway_E2E
  timeoutInMinutes: 150
  steps:
  - template: templates/e2e-steps.yml
- job: Run_KubeEgressGateway_E2E_Nodesubnet
  timeoutInMinutes: 150
  steps:
  - template: templates/e2e-steps.yml
    parameters:
      networkPlugin: 'azure'
- job: Run_KubeEgressGateway_E2E_Cilium
  timeoutInMinutes: 150
  steps:
  - template: templates/e2e-steps.yml
    parameters:
      networkPlugin: 'cilium'

