resources:
- manager.yaml
generatorOptions:
  disableNameSuffixHash: true

patches:
  # Mount the controller config file for loading manager configurations
  # through a ComponentConfig type
  - path: manager_config_patch.yaml