resources:
- manager.yaml
generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
  # Mount the controller config file for loading manager configurations
  # through a ComponentConfig type
  - manager_config_patch.yaml