---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kube-egress-gateway-microsoft-com-v1alpha1-staticgatewayconfiguration
  failurePolicy: Fail
  name: mstaticgatewayconfiguration.kb.io
  rules:
  - apiGroups:
    - egressgateway.kubernetes.azure.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - staticgatewayconfigurations
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kube-egress-gateway-microsoft-com-v1alpha1-staticgatewayconfiguration
  failurePolicy: Fail
  name: vstaticgatewayconfiguration.kb.io
  rules:
  - apiGroups:
    - egressgateway.kubernetes.azure.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - staticgatewayconfigurations
  sideEffects: None
