# permissions for end users to edit gatewaywireguardendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatewaywireguardendpoint-editor-role
rules:
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - gatewaywireguardendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - gatewaywireguardendpoints/status
  verbs:
  - get
