# permissions for end users to edit podwireguardendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podwireguardendpoint-editor-role
rules:
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - podwireguardendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - podwireguardendpoints/status
  verbs:
  - get
