---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - staticgatewayconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-egress-gateway.microsoft.com
  resources:
  - staticgatewayconfigurations/status
  verbs:
  - get
  - patch
  - update
