apiVersion: egressgateway.kubernetes.azure.com/v1alpha1
kind: GatewayLBConfiguration
metadata:
  labels:
    app.kubernetes.io/name: gatewaylbconfiguration
    app.kubernetes.io/instance: gatewaylbconfiguration-sample
    app.kubernetes.io/part-of: kube-egress-gateway
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-egress-gateway
  name: gatewaylbconfiguration-sample
spec:
  gatewayNodepoolName: gwnodepool
  gatewayVmssProfile: {}
  provisionPublicIps: true
