apiVersion: kube-egress-gateway.microsoft.com/v1alpha1
kind: StaticGatewayConfiguration
metadata:
  name: staticgatewayconfiguration-sample
spec:
  gatewayNodepoolName: gatewaypool1
  gatewayVmssProfile:
    vmssResourceGroup: gw-rg
    vmssName: gatewaypool1-12345678-vmss
  exceptionCIDRs:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 120.123.0.0/16
  publicIpPrefixId: /subscriptions/<subscription_id>/resourceGroups/<rg_name>/providers/Microsoft.Network/publicIPPrefixes/<prefix_name>
