apiVersion: kube-egress-gateway.microsoft.com/v1alpha1
kind: StaticGatewayConfiguration
metadata:
  name: staticgatewayconfiguration-sample
spec:
  gatewayNodepoolName: gwnodepool
  gatewayVmssProfile:
    vmssResourceGroup: gw-rg
    vmssName: gatewaypool1-12345678-vmss
    publicIpPrefixSize: 31
  # publicIpPrefixId: /subscriptions/<subscription_id>/resourceGroups/<rg_name>/providers/Microsoft.Network/publicIPPrefixes/<prefix_name>
