apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: daemon
        volumeMounts:
        - name: daemon-config-volume
          mountPath: /etc/config
      volumes:
      - name: daemon-config-volume
        configMap:
          name: kube-egress-gateway-azure-cloud-config
