# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/egressgateway.kubernetes.azure.com_staticgatewayconfigurations.yaml
- bases/egressgateway.kubernetes.azure.com_podendpoints.yaml
- bases/egressgateway.kubernetes.azure.com_gatewaylbconfigurations.yaml
- bases/egressgateway.kubernetes.azure.com_gatewayvmconfigurations.yaml
- bases/egressgateway.kubernetes.azure.com_gatewaystatuses.yaml
#+kubebuilder:scaffold:crdkustomizeresource

configurations:
- kustomizeconfig.yaml
