apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    kubernetes.azure.com/static-gateway-configuration: sgw1 # required
spec:
  containers:
    - name: samplepod
      command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
      image: alpine
