//
// MIT License
//
// Copyright (c) Microsoft Corporation.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pkg/cniprotocol/v1/cni.proto

package v1

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodName      string `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace string `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
}

func (x *PodInfo) Reset() {
	*x = PodInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfo) ProtoMessage() {}

func (x *PodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfo.ProtoReflect.Descriptor instead.
func (*PodInfo) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP(), []int{0}
}

func (x *PodInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodInfo) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

// CNIAddRequest is the request for cni add function.
type NicAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodConfig  *PodInfo `protobuf:"bytes,1,opt,name=pod_config,json=podConfig,proto3" json:"pod_config,omitempty"`
	ListenPort int32    `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	AllowedIp  []string `protobuf:"bytes,3,rep,name=allowed_ip,json=allowedIp,proto3" json:"allowed_ip,omitempty"`
	PublicKey  string   `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *NicAddRequest) Reset() {
	*x = NicAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NicAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicAddRequest) ProtoMessage() {}

func (x *NicAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicAddRequest.ProtoReflect.Descriptor instead.
func (*NicAddRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP(), []int{1}
}

func (x *NicAddRequest) GetPodConfig() *PodInfo {
	if x != nil {
		return x.PodConfig
	}
	return nil
}

func (x *NicAddRequest) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *NicAddRequest) GetAllowedIp() []string {
	if x != nil {
		return x.AllowedIp
	}
	return nil
}

func (x *NicAddRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// CNIAddResponse is the response for cni add function.
type NicAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	EndpointIp string         `protobuf:"bytes,2,opt,name=endpoint_ip,json=endpointIp,proto3" json:"endpoint_ip,omitempty"`
	ListenPort int32          `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	PublicKey  string         `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *NicAddResponse) Reset() {
	*x = NicAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NicAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicAddResponse) ProtoMessage() {}

func (x *NicAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicAddResponse.ProtoReflect.Descriptor instead.
func (*NicAddResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP(), []int{2}
}

func (x *NicAddResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *NicAddResponse) GetEndpointIp() string {
	if x != nil {
		return x.EndpointIp
	}
	return ""
}

func (x *NicAddResponse) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *NicAddResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// CNIDeleteRequest is the request for cni del function.
type NicDelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodConfig *PodInfo `protobuf:"bytes,1,opt,name=pod_config,json=podConfig,proto3" json:"pod_config,omitempty"`
}

func (x *NicDelRequest) Reset() {
	*x = NicDelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NicDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicDelRequest) ProtoMessage() {}

func (x *NicDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicDelRequest.ProtoReflect.Descriptor instead.
func (*NicDelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP(), []int{3}
}

func (x *NicDelRequest) GetPodConfig() *PodInfo {
	if x != nil {
		return x.PodConfig
	}
	return nil
}

// CNIDeleteResponse is the response for cni del function.
type NicDelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *NicDelResponse) Reset() {
	*x = NicDelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NicDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicDelResponse) ProtoMessage() {}

func (x *NicDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicDelResponse.ProtoReflect.Descriptor instead.
func (*NicDelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP(), []int{4}
}

func (x *NicDelResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_pkg_cniprotocol_v1_cni_proto protoreflect.FileDescriptor

var file_pkg_cniprotocol_v1_cni_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6e, 0x69, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6e, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x70, 0x6b, 0x67, 0x2e, 0x63, 0x6e, 0x69, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x76, 0x31, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x07, 0x50,
	0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xaa, 0x01, 0x0a, 0x0d, 0x4e, 0x69, 0x63, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x70, 0x6f, 0x64, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70,
	0x6b, 0x67, 0x2e, 0x63, 0x6e, 0x69, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x70, 0x6f, 0x64, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64,
	0x5f, 0x69, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x49, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x22, 0x9d, 0x01, 0x0a, 0x0e, 0x4e, 0x69, 0x63, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x69,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x49, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x50, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x22, 0x4b, 0x0a, 0x0d, 0x4e, 0x69, 0x63, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x70, 0x6f, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x63,
	0x6e, 0x69, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x70, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x22, 0x3c, 0x0a, 0x0e, 0x4e, 0x69, 0x63, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xae,
	0x01, 0x0a, 0x0a, 0x4e, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a,
	0x06, 0x4e, 0x69, 0x63, 0x41, 0x64, 0x64, 0x12, 0x21, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x63, 0x6e,
	0x69, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x69, 0x63,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x6b, 0x67,
	0x2e, 0x63, 0x6e, 0x69, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x4e, 0x69, 0x63, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f,
	0x0a, 0x06, 0x4e, 0x69, 0x63, 0x44, 0x65, 0x6c, 0x12, 0x21, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x63,
	0x6e, 0x69, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x69,
	0x63, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x6b,
	0x67, 0x2e, 0x63, 0x6e, 0x69, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x4e, 0x69, 0x63, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x7a,
	0x75, 0x72, 0x65, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x2d, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2d,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6e, 0x69, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_cniprotocol_v1_cni_proto_rawDescOnce sync.Once
	file_pkg_cniprotocol_v1_cni_proto_rawDescData = file_pkg_cniprotocol_v1_cni_proto_rawDesc
)

func file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP() []byte {
	file_pkg_cniprotocol_v1_cni_proto_rawDescOnce.Do(func() {
		file_pkg_cniprotocol_v1_cni_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_cniprotocol_v1_cni_proto_rawDescData)
	})
	return file_pkg_cniprotocol_v1_cni_proto_rawDescData
}

var file_pkg_cniprotocol_v1_cni_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_cniprotocol_v1_cni_proto_goTypes = []interface{}{
	(*PodInfo)(nil),        // 0: pkg.cniprotocol.v1.PodInfo
	(*NicAddRequest)(nil),  // 1: pkg.cniprotocol.v1.NicAddRequest
	(*NicAddResponse)(nil), // 2: pkg.cniprotocol.v1.NicAddResponse
	(*NicDelRequest)(nil),  // 3: pkg.cniprotocol.v1.NicDelRequest
	(*NicDelResponse)(nil), // 4: pkg.cniprotocol.v1.NicDelResponse
	(*status.Status)(nil),  // 5: google.rpc.Status
}
var file_pkg_cniprotocol_v1_cni_proto_depIdxs = []int32{
	0, // 0: pkg.cniprotocol.v1.NicAddRequest.pod_config:type_name -> pkg.cniprotocol.v1.PodInfo
	5, // 1: pkg.cniprotocol.v1.NicAddResponse.status:type_name -> google.rpc.Status
	0, // 2: pkg.cniprotocol.v1.NicDelRequest.pod_config:type_name -> pkg.cniprotocol.v1.PodInfo
	5, // 3: pkg.cniprotocol.v1.NicDelResponse.status:type_name -> google.rpc.Status
	1, // 4: pkg.cniprotocol.v1.NicService.NicAdd:input_type -> pkg.cniprotocol.v1.NicAddRequest
	3, // 5: pkg.cniprotocol.v1.NicService.NicDel:input_type -> pkg.cniprotocol.v1.NicDelRequest
	2, // 6: pkg.cniprotocol.v1.NicService.NicAdd:output_type -> pkg.cniprotocol.v1.NicAddResponse
	4, // 7: pkg.cniprotocol.v1.NicService.NicDel:output_type -> pkg.cniprotocol.v1.NicDelResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_cniprotocol_v1_cni_proto_init() }
func file_pkg_cniprotocol_v1_cni_proto_init() {
	if File_pkg_cniprotocol_v1_cni_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_cniprotocol_v1_cni_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_cniprotocol_v1_cni_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NicAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_cniprotocol_v1_cni_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NicAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_cniprotocol_v1_cni_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NicDelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_cniprotocol_v1_cni_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NicDelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_cniprotocol_v1_cni_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_cniprotocol_v1_cni_proto_goTypes,
		DependencyIndexes: file_pkg_cniprotocol_v1_cni_proto_depIdxs,
		MessageInfos:      file_pkg_cniprotocol_v1_cni_proto_msgTypes,
	}.Build()
	File_pkg_cniprotocol_v1_cni_proto = out.File
	file_pkg_cniprotocol_v1_cni_proto_rawDesc = nil
	file_pkg_cniprotocol_v1_cni_proto_goTypes = nil
	file_pkg_cniprotocol_v1_cni_proto_depIdxs = nil
}
