// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: pkg/cniprotocol/v1/cni.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultRoute int32

const (
	DefaultRoute_DEFAULT_ROUTE_UNSPECIFIED           DefaultRoute = 0
	DefaultRoute_DEFAULT_ROUTE_STATIC_EGRESS_GATEWAY DefaultRoute = 1
	DefaultRoute_DEFAULT_ROUTE_AZURE_NETWORKING      DefaultRoute = 2
)

// Enum value maps for DefaultRoute.
var (
	DefaultRoute_name = map[int32]string{
		0: "DEFAULT_ROUTE_UNSPECIFIED",
		1: "DEFAULT_ROUTE_STATIC_EGRESS_GATEWAY",
		2: "DEFAULT_ROUTE_AZURE_NETWORKING",
	}
	DefaultRoute_value = map[string]int32{
		"DEFAULT_ROUTE_UNSPECIFIED":           0,
		"DEFAULT_ROUTE_STATIC_EGRESS_GATEWAY": 1,
		"DEFAULT_ROUTE_AZURE_NETWORKING":      2,
	}
)

func (x DefaultRoute) Enum() *DefaultRoute {
	p := new(DefaultRoute)
	*p = x
	return p
}

func (x DefaultRoute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefaultRoute) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_cniprotocol_v1_cni_proto_enumTypes[0].Descriptor()
}

func (DefaultRoute) Type() protoreflect.EnumType {
	return &file_pkg_cniprotocol_v1_cni_proto_enumTypes[0]
}

func (x DefaultRoute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefaultRoute.Descriptor instead.
func (DefaultRoute) EnumDescriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP(), []int{0}
}

type PodInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodInfo) Reset() {
	*x = PodInfo{}
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfo) ProtoMessage() {}

func (x *PodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfo.ProtoReflect.Descriptor instead.
func (*PodInfo) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP(), []int{0}
}

func (x *PodInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodInfo) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

// CNIAddRequest is the request for cni add function.
type NicAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodConfig     *PodInfo               `protobuf:"bytes,1,opt,name=pod_config,json=podConfig,proto3" json:"pod_config,omitempty"`
	ListenPort    int32                  `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	AllowedIp     string                 `protobuf:"bytes,3,opt,name=allowed_ip,json=allowedIp,proto3" json:"allowed_ip,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	GatewayName   string                 `protobuf:"bytes,5,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NicAddRequest) Reset() {
	*x = NicAddRequest{}
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NicAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicAddRequest) ProtoMessage() {}

func (x *NicAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicAddRequest.ProtoReflect.Descriptor instead.
func (*NicAddRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP(), []int{1}
}

func (x *NicAddRequest) GetPodConfig() *PodInfo {
	if x != nil {
		return x.PodConfig
	}
	return nil
}

func (x *NicAddRequest) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *NicAddRequest) GetAllowedIp() string {
	if x != nil {
		return x.AllowedIp
	}
	return ""
}

func (x *NicAddRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *NicAddRequest) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

// CNIAddResponse is the response for cni add function.
type NicAddResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EndpointIp     string                 `protobuf:"bytes,1,opt,name=endpoint_ip,json=endpointIp,proto3" json:"endpoint_ip,omitempty"`
	ListenPort     int32                  `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	PublicKey      string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	ExceptionCidrs []string               `protobuf:"bytes,4,rep,name=exception_cidrs,json=exceptionCidrs,proto3" json:"exception_cidrs,omitempty"`
	DefaultRoute   DefaultRoute           `protobuf:"varint,5,opt,name=default_route,json=defaultRoute,proto3,enum=pkg.cniprotocol.v1.DefaultRoute" json:"default_route,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NicAddResponse) Reset() {
	*x = NicAddResponse{}
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NicAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicAddResponse) ProtoMessage() {}

func (x *NicAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicAddResponse.ProtoReflect.Descriptor instead.
func (*NicAddResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP(), []int{2}
}

func (x *NicAddResponse) GetEndpointIp() string {
	if x != nil {
		return x.EndpointIp
	}
	return ""
}

func (x *NicAddResponse) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *NicAddResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *NicAddResponse) GetExceptionCidrs() []string {
	if x != nil {
		return x.ExceptionCidrs
	}
	return nil
}

func (x *NicAddResponse) GetDefaultRoute() DefaultRoute {
	if x != nil {
		return x.DefaultRoute
	}
	return DefaultRoute_DEFAULT_ROUTE_UNSPECIFIED
}

// CNIDeleteRequest is the request for cni del function.
type NicDelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodConfig     *PodInfo               `protobuf:"bytes,1,opt,name=pod_config,json=podConfig,proto3" json:"pod_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NicDelRequest) Reset() {
	*x = NicDelRequest{}
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NicDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicDelRequest) ProtoMessage() {}

func (x *NicDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicDelRequest.ProtoReflect.Descriptor instead.
func (*NicDelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP(), []int{3}
}

func (x *NicDelRequest) GetPodConfig() *PodInfo {
	if x != nil {
		return x.PodConfig
	}
	return nil
}

// CNIDeleteResponse is the response for cni del function.
type NicDelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NicDelResponse) Reset() {
	*x = NicDelResponse{}
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NicDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicDelResponse) ProtoMessage() {}

func (x *NicDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicDelResponse.ProtoReflect.Descriptor instead.
func (*NicDelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP(), []int{4}
}

// PodRetrieveRequest is the request for retrieving pod function.
type PodRetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodConfig     *PodInfo               `protobuf:"bytes,1,opt,name=pod_config,json=podConfig,proto3" json:"pod_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodRetrieveRequest) Reset() {
	*x = PodRetrieveRequest{}
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodRetrieveRequest) ProtoMessage() {}

func (x *PodRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodRetrieveRequest.ProtoReflect.Descriptor instead.
func (*PodRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP(), []int{5}
}

func (x *PodRetrieveRequest) GetPodConfig() *PodInfo {
	if x != nil {
		return x.PodConfig
	}
	return nil
}

// PodRetrieveResponse is the response for retrieving pod function.
type PodRetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Annotations   map[string]string      `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodRetrieveResponse) Reset() {
	*x = PodRetrieveResponse{}
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodRetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodRetrieveResponse) ProtoMessage() {}

func (x *PodRetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cniprotocol_v1_cni_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodRetrieveResponse.ProtoReflect.Descriptor instead.
func (*PodRetrieveResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP(), []int{6}
}

func (x *PodRetrieveResponse) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_pkg_cniprotocol_v1_cni_proto protoreflect.FileDescriptor

const file_pkg_cniprotocol_v1_cni_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/cniprotocol/v1/cni.proto\x12\x12pkg.cniprotocol.v1\"I\n" +
	"\aPodInfo\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\"\xcd\x01\n" +
	"\rNicAddRequest\x12:\n" +
	"\n" +
	"pod_config\x18\x01 \x01(\v2\x1b.pkg.cniprotocol.v1.PodInfoR\tpodConfig\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\x05R\n" +
	"listenPort\x12\x1d\n" +
	"\n" +
	"allowed_ip\x18\x03 \x01(\tR\tallowedIp\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12!\n" +
	"\fgateway_name\x18\x05 \x01(\tR\vgatewayName\"\xe1\x01\n" +
	"\x0eNicAddResponse\x12\x1f\n" +
	"\vendpoint_ip\x18\x01 \x01(\tR\n" +
	"endpointIp\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\x05R\n" +
	"listenPort\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12'\n" +
	"\x0fexception_cidrs\x18\x04 \x03(\tR\x0eexceptionCidrs\x12E\n" +
	"\rdefault_route\x18\x05 \x01(\x0e2 .pkg.cniprotocol.v1.DefaultRouteR\fdefaultRoute\"K\n" +
	"\rNicDelRequest\x12:\n" +
	"\n" +
	"pod_config\x18\x01 \x01(\v2\x1b.pkg.cniprotocol.v1.PodInfoR\tpodConfig\"\x10\n" +
	"\x0eNicDelResponse\"P\n" +
	"\x12PodRetrieveRequest\x12:\n" +
	"\n" +
	"pod_config\x18\x01 \x01(\v2\x1b.pkg.cniprotocol.v1.PodInfoR\tpodConfig\"\xb1\x01\n" +
	"\x13PodRetrieveResponse\x12Z\n" +
	"\vannotations\x18\x01 \x03(\v28.pkg.cniprotocol.v1.PodRetrieveResponse.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*z\n" +
	"\fDefaultRoute\x12\x1d\n" +
	"\x19DEFAULT_ROUTE_UNSPECIFIED\x10\x00\x12'\n" +
	"#DEFAULT_ROUTE_STATIC_EGRESS_GATEWAY\x10\x01\x12\"\n" +
	"\x1eDEFAULT_ROUTE_AZURE_NETWORKING\x10\x022\x8e\x02\n" +
	"\n" +
	"NicService\x12O\n" +
	"\x06NicAdd\x12!.pkg.cniprotocol.v1.NicAddRequest\x1a\".pkg.cniprotocol.v1.NicAddResponse\x12O\n" +
	"\x06NicDel\x12!.pkg.cniprotocol.v1.NicDelRequest\x1a\".pkg.cniprotocol.v1.NicDelResponse\x12^\n" +
	"\vPodRetrieve\x12&.pkg.cniprotocol.v1.PodRetrieveRequest\x1a'.pkg.cniprotocol.v1.PodRetrieveResponseB9Z7github.com/Azure/kube-egress-gateway/pkg/cniprotocol/v1b\x06proto3"

var (
	file_pkg_cniprotocol_v1_cni_proto_rawDescOnce sync.Once
	file_pkg_cniprotocol_v1_cni_proto_rawDescData []byte
)

func file_pkg_cniprotocol_v1_cni_proto_rawDescGZIP() []byte {
	file_pkg_cniprotocol_v1_cni_proto_rawDescOnce.Do(func() {
		file_pkg_cniprotocol_v1_cni_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_cniprotocol_v1_cni_proto_rawDesc), len(file_pkg_cniprotocol_v1_cni_proto_rawDesc)))
	})
	return file_pkg_cniprotocol_v1_cni_proto_rawDescData
}

var file_pkg_cniprotocol_v1_cni_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_cniprotocol_v1_cni_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_cniprotocol_v1_cni_proto_goTypes = []any{
	(DefaultRoute)(0),           // 0: pkg.cniprotocol.v1.DefaultRoute
	(*PodInfo)(nil),             // 1: pkg.cniprotocol.v1.PodInfo
	(*NicAddRequest)(nil),       // 2: pkg.cniprotocol.v1.NicAddRequest
	(*NicAddResponse)(nil),      // 3: pkg.cniprotocol.v1.NicAddResponse
	(*NicDelRequest)(nil),       // 4: pkg.cniprotocol.v1.NicDelRequest
	(*NicDelResponse)(nil),      // 5: pkg.cniprotocol.v1.NicDelResponse
	(*PodRetrieveRequest)(nil),  // 6: pkg.cniprotocol.v1.PodRetrieveRequest
	(*PodRetrieveResponse)(nil), // 7: pkg.cniprotocol.v1.PodRetrieveResponse
	nil,                         // 8: pkg.cniprotocol.v1.PodRetrieveResponse.AnnotationsEntry
}
var file_pkg_cniprotocol_v1_cni_proto_depIdxs = []int32{
	1, // 0: pkg.cniprotocol.v1.NicAddRequest.pod_config:type_name -> pkg.cniprotocol.v1.PodInfo
	0, // 1: pkg.cniprotocol.v1.NicAddResponse.default_route:type_name -> pkg.cniprotocol.v1.DefaultRoute
	1, // 2: pkg.cniprotocol.v1.NicDelRequest.pod_config:type_name -> pkg.cniprotocol.v1.PodInfo
	1, // 3: pkg.cniprotocol.v1.PodRetrieveRequest.pod_config:type_name -> pkg.cniprotocol.v1.PodInfo
	8, // 4: pkg.cniprotocol.v1.PodRetrieveResponse.annotations:type_name -> pkg.cniprotocol.v1.PodRetrieveResponse.AnnotationsEntry
	2, // 5: pkg.cniprotocol.v1.NicService.NicAdd:input_type -> pkg.cniprotocol.v1.NicAddRequest
	4, // 6: pkg.cniprotocol.v1.NicService.NicDel:input_type -> pkg.cniprotocol.v1.NicDelRequest
	6, // 7: pkg.cniprotocol.v1.NicService.PodRetrieve:input_type -> pkg.cniprotocol.v1.PodRetrieveRequest
	3, // 8: pkg.cniprotocol.v1.NicService.NicAdd:output_type -> pkg.cniprotocol.v1.NicAddResponse
	5, // 9: pkg.cniprotocol.v1.NicService.NicDel:output_type -> pkg.cniprotocol.v1.NicDelResponse
	7, // 10: pkg.cniprotocol.v1.NicService.PodRetrieve:output_type -> pkg.cniprotocol.v1.PodRetrieveResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_cniprotocol_v1_cni_proto_init() }
func file_pkg_cniprotocol_v1_cni_proto_init() {
	if File_pkg_cniprotocol_v1_cni_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_cniprotocol_v1_cni_proto_rawDesc), len(file_pkg_cniprotocol_v1_cni_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_cniprotocol_v1_cni_proto_goTypes,
		DependencyIndexes: file_pkg_cniprotocol_v1_cni_proto_depIdxs,
		EnumInfos:         file_pkg_cniprotocol_v1_cni_proto_enumTypes,
		MessageInfos:      file_pkg_cniprotocol_v1_cni_proto_msgTypes,
	}.Build()
	File_pkg_cniprotocol_v1_cni_proto = out.File
	file_pkg_cniprotocol_v1_cni_proto_goTypes = nil
	file_pkg_cniprotocol_v1_cni_proto_depIdxs = nil
}
