// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/iptableswrapper/iptables.go

// Package mockiptableswrapper is a generated GoMock package.
package mockiptableswrapper

import (
	reflect "reflect"

	iptableswrapper "github.com/Azure/kube-egress-gateway/pkg/iptableswrapper"
	gomock "github.com/golang/mock/gomock"
)

// MockIpTables is a mock of IpTables interface.
type MockIpTables struct {
	ctrl     *gomock.Controller
	recorder *MockIpTablesMockRecorder
}

// MockIpTablesMockRecorder is the mock recorder for MockIpTables.
type MockIpTablesMockRecorder struct {
	mock *MockIpTables
}

// NewMockIpTables creates a new mock instance.
func NewMockIpTables(ctrl *gomock.Controller) *MockIpTables {
	mock := &MockIpTables{ctrl: ctrl}
	mock.recorder = &MockIpTablesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpTables) EXPECT() *MockIpTablesMockRecorder {
	return m.recorder
}

// AppendUnique mocks base method.
func (m *MockIpTables) AppendUnique(table, chain string, rulespec ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{table, chain}
	for _, a := range rulespec {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AppendUnique", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendUnique indicates an expected call of AppendUnique.
func (mr *MockIpTablesMockRecorder) AppendUnique(table, chain interface{}, rulespec ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{table, chain}, rulespec...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendUnique", reflect.TypeOf((*MockIpTables)(nil).AppendUnique), varargs...)
}

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockInterface) New() (iptableswrapper.IpTables, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(iptableswrapper.IpTables)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockInterfaceMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockInterface)(nil).New))
}
